spring:
        datasource:
            url: jdbc:postgresql://localhost:5432/Imobiliaria
            username: postgres
            password: 123456
        jpa:
            hibernate:
                ddlAuto: update
            showSql: true
        redis:
            host:  localhost
            port:  6379
        cache:
            type: redis
            
          
            
